### ISSUE TITLE
Fucked up #2

### ISSUE THREAD

**Issue by damixk** [edaku/daku#3]
Commit není náhrada za ctr+s.
@Hribek stahuje zdroják připlácá k němu pár svých kousíčků a myslí si, že hotovo.
Neodkazuje se na nic co by mohlo ten super kod napsanej v main.js rozjet.
Dokonce neodkazuje na samotný main.js. 

Odkazy taky nic nedělají a půlka z nich ani neví, že jsou odkaz.

A pokud už kopíruju ze stacku. Neberu to z toho kde člověk prosí o radu nýbrž od lidí co mu radí.
Netrvalo dlouho než sem našel <a href="http://stackoverflow.com/questions/20399970/jquery-drop-down-menu-not-working"> něco </a> co se podobá tomu v main.js.

Takže za mě :-1: a -:100: bludištáků

**Comment by kubp** [comment]
:+1:

**Comment by damixk** [comment]
Už se něco stalo tak
