### ISSUE TITLE
Grafik

### ISSUE THREAD

**Issue by damixk** [edaku/daku#5]
Grafik stojí za pěkný :hankey: 

Když nevím jak něco udělat tak se do toho neseru. Cssko je tak přeplácaný, že kdyby neexistovalo vyhledávání tak to dělám doteď. 

###### Hezké css
Někdy je tam  jeden styl i vícekrát asi pro jistotu. Škoda jen, že prohlížeče na to kašlou a berou poslední. Navíc je to nadčasové a počítáme se styly pro věci které nejsou ani definované.:astonished: 

###### Možná přijde i kouzelník
Takový **YOLO** věci jako `opacity:1`, `margin-right:35px;` nebo `margin-left:0px;` mě dostávají.
Mimochodem ten margin-right byl spojený s `width:100%` a paddingem. Není pak divu, že to lítá kde nemá. #4  A pokud na něčem pracuji tak to dodělám dokonce, protože teď v cssku (a nejenom tam) lítá zakomentovaný kus kódu který nevím co tam k***a dělá když nefunguje.

###### Verzování i v souborech
 Dneska se mi dokonce zdál sen kde byl zdroják unifikovanej a odkazy fungovaly. Bohužel jsem se probudil do drsné reality a řekl jsem si, že se to změní. No po 3 hodinách civění do zdrojáku kterej nevím jak může fungovat jsem to vzdal. 

Takže vás prosím řestanťe to :smoking: díky.

**Comment by kubp** [comment]
Všechno jsem přepsal. Použil jsem LESS protože se v tom cssku nedalo vyznat.:sweat:
@Hribek :-1:

**Comment by damixk** [comment]
^ :+1:

**Comment by damixk** [comment]
@kubp :+1:
