### ISSUE TITLE
Další díl ze série 10 dní bez commitu

### ISSUE THREAD

**Issue by damixk** [edaku/daku#6]
Další super commit. Asi jedeme na najvíc issue nebo tak něco. Kdyby to bylo aspoň omylem a ne nedbalostí.
### Odesíláme si data pro radost
__Pan google__
![bez nazvu](https://cloud.githubusercontent.com/assets/7703131/7544823/0695d392-f5d1-11e4-9e71-3992a50e0801.png)
__Chtěli jsme ajax, tak ho máme__
![ajax](https://cloud.githubusercontent.com/assets/7703131/7545011/8881b046-f5d2-11e4-9aa8-ad369e77e4c0.png)

### Validní až to červená
![bug](https://cloud.githubusercontent.com/assets/7703131/7544773/78f5d7a8-f5d0-11e4-85aa-9719f1c6e2de.png)
__Někdo na něco zapoměl__
![bug2](https://cloud.githubusercontent.com/assets/7703131/7544807/d85abcf4-f5d0-11e4-8cf3-80d89d319f7c.png)
__Chudák div nemá kamarády__
![chudak](https://cloud.githubusercontent.com/assets/7703131/7544910/c53d1a12-f5d1-11e4-9a36-7c49e52f482f.png)

### Chybka sem, chybka tam
__A najednou 29 errorů__
![disappointed-terrible-awful-omg-embarassed-embarassing-wtf-fgif](https://cloud.githubusercontent.com/assets/7703131/7544943/eeb61042-f5d1-11e4-8784-28cdb2d2abeb.gif)

### Komentáře které se dají číst
    //PoÄŤet prodanĂ˝ch za  hodinu
    //VytvoĹ™enĂ­ novĂ©ho Ĺ™Ăˇdku
    //vytvoĹ™enĂ­ Ĺ™Ăˇdku na Ăşpravu
    //Ăšprava konkrĂ©tnĂ­ho Ĺ™Ăˇdku

**Comment by kubp** [comment]
@Hribek by se k tomu třeba mohl vyjádřit.

 <img src="http://sd.keepcalm-o-matic.co.uk/i/stop-wanking-and-do-some-work.png">

**Comment by damixk** [comment]
<img src="http://www.kupsi-tapety.cz/files/products_images/product_big/0/5678_image.jpg">

**Comment by kubp** [comment]
<img src="http://24.media.tumblr.com/tumblr_ma0cjtycmI1rpf23po1_250.gif">

**Comment by kubp** [comment]
@Hribek 
<img src="http://www.funnypica.com/wp-content/uploads/2012/05/Ugly-People-Pictures-FunnyPica.com_.jpg">

**Comment by kubp** [comment]
@Hribek Už se nemusíš snažit. Backend zítra dodělám. 

https://dev.drojd.cz/backend/

**Comment by damixk** [comment]
No dobrý tak jsme to dali (Hříbek ne).
